version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre_Building...

  build:
    command:
      - echo Building Docker Image...

    post_build:
      commands:
        - echo Pushing Image To ECR-Instance...
