apiVersion: apps/v1
kind: Deployment
metadata:
  name: lswebapp-deployment
  labels:
    app: lswebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lswebapp
  template:
    metadata:
      labels:
        app: lswebapp
    spec:
      containers:
        - name: lswebapp
          image: vbabiandboogk/localstorageplay
          ports:
            containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: lswebapp-service
spec:
  type: NodePort
  selector:
    app: lswebapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300
